/**
 * Renders the runner's in-memory state into a self-contained `.canvas.tsx`
 * file. The IDE hot-recompiles on file change, so calling write() repeatedly
 * gives the user a live view of the DAG run.
 *
 * The canvas is fully static React + cursor/canvas — all state is inlined as
 * a `const STATE = {...}` literal. Only that literal changes between writes;
 * the rendered template is identical.
 */

import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import type { Complexity, DAG } from "./dag.js";

export type TaskStatus = "PENDING" | "RUNNING" | "FINISHED" | "ERROR";

export interface TaskState {
  id: string;
  depends_on: string[];
  complexity: Complexity;
  subtask_prompt: string;
  status: TaskStatus;
  model: string;
  startedAt?: number;
  finishedAt?: number;
  resultText?: string;
  errorMessage?: string;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
}

export interface RunState {
  title: string;
  startedAt: number;
  finishedAt?: number;
  runOutcome?: "SUCCESS" | "FAILED" | "INTERRUPTED";
  runMessage?: string;
  tasks: TaskState[];
}

export function initialRunState(dag: DAG, modelFor: (c: Complexity) => string): RunState {
  return {
    title: dag.title,
    startedAt: Date.now(),
    tasks: dag.tasks.map((t) => ({
      id: t.id,
      depends_on: t.depends_on,
      complexity: t.complexity,
      subtask_prompt: t.subtask_prompt,
      status: "PENDING",
      model: modelFor(t.complexity),
    })),
  };
}

/**
 * Debounced writer. Multiple write() calls inside the debounce window collapse
 * into one filesystem write — the latest state always wins.
 */
export class CanvasWriter {
  private pending: RunState | null = null;
  private timer: NodeJS.Timeout | null = null;
  private inFlight: Promise<void> = Promise.resolve();
  private writeSeq = 0;
  private lastFailedWriteSeq = 0;
  private lastWriteError: unknown = null;

  constructor(
    private readonly canvasPath: string,
    private readonly debounceMs: number = 200,
  ) {}

  schedule(state: RunState): void {
    this.pending = state;
    if (this.timer) return;
    this.timer = setTimeout(() => {
      this.timer = null;
      const snapshot = this.pending;
      this.pending = null;
      if (snapshot) {
        this.enqueueWrite(snapshot);
      }
    }, this.debounceMs);
  }

  /** Force-flush any pending write and await disk completion. */
  async flush(): Promise<void> {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
    const snapshot = this.pending;
    this.pending = null;
    const targetWriteSeq = snapshot ? this.enqueueWrite(snapshot) : this.writeSeq;
    await this.inFlight;
    if (targetWriteSeq > 0 && this.lastFailedWriteSeq === targetWriteSeq) {
      throw this.lastWriteError;
    }
  }

  private enqueueWrite(state: RunState): number {
    const seq = ++this.writeSeq;
    this.inFlight = this.inFlight.then(async () => {
      try {
        await this.writeNow(state);
        if (this.lastFailedWriteSeq < seq) {
          this.lastWriteError = null;
        }
      } catch (err) {
        this.lastFailedWriteSeq = seq;
        this.lastWriteError = err;
      }
    });
    return seq;
  }

  private async writeNow(state: RunState): Promise<void> {
    const source = renderCanvasSource(state);
    await mkdir(dirname(this.canvasPath), { recursive: true });
    await writeFile(this.canvasPath, source, "utf8");
  }
}

function renderCanvasSource(state: RunState): string {
  const stateLiteral = JSON.stringify(state, null, 2);
  return `${HEADER}\n\nconst STATE: RunState = ${stateLiteral};\n\n${BODY}\n`;
}

const HEADER = `/* AUTO-GENERATED by sdk/dag-task-runner. Do not edit by hand — the runner overwrites this file. */
import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Text,
  computeDAGLayout,
  useHostTheme,
} from 'cursor/canvas';
import { useEffect, useMemo, useState } from 'react';

type TaskStatus = 'PENDING' | 'RUNNING' | 'FINISHED' | 'ERROR';
type Complexity = 'HIGH' | 'MED' | 'LOW';

interface TaskState {
  id: string;
  depends_on: string[];
  complexity: Complexity;
  subtask_prompt: string;
  status: TaskStatus;
  model: string;
  startedAt?: number;
  finishedAt?: number;
  resultText?: string;
  errorMessage?: string;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
}

interface RunState {
  title: string;
  startedAt: number;
  finishedAt?: number;
  runOutcome?: 'SUCCESS' | 'FAILED' | 'INTERRUPTED';
  runMessage?: string;
  tasks: TaskState[];
}`;

const BODY = `export default function DagRun(): JSX.Element {
  return <div>DAG Canvas</div>;
}`;
