#!/usr/bin/env node
/**
 * Cross-platform env generation for Copilot cloud setup (Linux CI).
 * Mirrors generate-env.ps1 using launch-manifest + folder hash slot logic.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");

function getAppPort(manifest, appId) {
  const app = manifest.apps.find((a) => a.id === appId);
  if (!app?.port) throw new Error(`Port not defined for app '${appId}'`);
  return app.port;
}

function allocatePorts(worktreePath) {
  const manifest = JSON.parse(
    readFileSync(join(ROOT, "scripts/launch-manifest.json"), "utf8")
  );
  const folderName = basename(worktreePath);
  const hash = createHash("sha256").update(folderName).digest();
  const slot = hash[0] % 10;
  const offset = slot * 10;
  const ids = [
    "vibe-web-app",
    "web-dashboard",
    "agent-server",
    "example-next",
    "example-react",
    "forge-app",
    "forge-web",
    "forge-api",
    "forge-docs",
    "forge-storybook",
  ];
  const envKeys = [
    "VIBE_WEB_PORT",
    "WEB_DASHBOARD_PORT",
    "AGENT_SERVER_PORT",
    "EXAMPLE_NEXT_PORT",
    "EXAMPLE_REACT_PORT",
    "FORGE_APP_PORT",
    "FORGE_WEB_PORT",
    "FORGE_API_PORT",
    "FORGE_DOCS_PORT",
    "FORGE_STORYBOOK_PORT",
  ];
  const ports = { WORKTREE_SLOT: slot };
  ids.forEach((id, i) => {
    ports[envKeys[i]] = getAppPort(manifest, id) + offset;
  });
  ports.NEXT_PUBLIC_AGENT_SERVER_WS_URL = `ws://localhost:${ports.AGENT_SERVER_PORT}/ws/agent`;
  return ports;
}

const worktreeRoot =
  process.env.COPILOT_WORKSPACE_PATH ?? process.env.GITHUB_WORKSPACE ?? ROOT;
const sourceRoot =
  process.env.COPILOT_ROOT_PATH ?? process.env.ROOT_WORKTREE_PATH ?? ROOT;
const ports = allocatePorts(worktreeRoot);
const prBase =
  process.env.COPILOT_DEFAULT_BRANCH &&
  process.env.COPILOT_DEFAULT_BRANCH !== "main"
    ? process.env.COPILOT_DEFAULT_BRANCH
    : "dev";

const copilotDir = join(worktreeRoot, ".copilot");
mkdirSync(copilotDir, { recursive: true });

const lines = [
  "# Auto-generated by scripts/copilot-workspace/generate-env.mjs — do not commit",
  `MODME_WORKSPACE_NAME=${process.env.COPILOT_WORKSPACE_NAME ?? ""}`,
  `MODME_WORKSPACE_PATH=${worktreeRoot}`,
  `MODME_ROOT_PATH=${sourceRoot}`,
  `MODME_PR_BASE_BRANCH=${prBase}`,
  `COPILOT_SCRIPT_TRIGGER=${process.env.COPILOT_SCRIPT_TRIGGER ?? ""}`,
  `COPILOT_PORT=${process.env.COPILOT_PORT ?? ports.FORGE_APP_PORT}`,
  `WORKTREE_SLOT=${ports.WORKTREE_SLOT}`,
  ...Object.entries(ports)
    .filter(([k]) => k !== "WORKTREE_SLOT")
    .map(([k, v]) => `${k}=${v}`),
];

const outFile = join(copilotDir, "workspace.generated.env");
writeFileSync(outFile, `${lines.join("\n")}\n`, "utf8");

const portsFile = join(worktreeRoot, ".worktree-ports.env");
if (!existsSync(portsFile)) {
  const portLines = [
    "# Auto-generated by generate-env.mjs",
    `WORKTREE_SLOT=${ports.WORKTREE_SLOT}`,
    ...Object.entries(ports)
      .filter(([k]) => k !== "WORKTREE_SLOT")
      .map(([k, v]) => `${k}=${v}`),
  ];
  writeFileSync(portsFile, `${portLines.join("\n")}\n`, "utf8");
}

console.log(`Wrote ${outFile}`);
