#Requires -Version 5.1
<#
.SYNOPSIS
  Write .copilot/workspace.generated.env from COPILOT_* vars and worktree port allocation.
#>
param(
  [string]$WorktreePath = '',
  [switch]$Help
)

$ErrorActionPreference = 'Stop'

if ($Help) {
  @'
generate-env.ps1 — map COPILOT_* to ModMe workspace env

Writes .copilot/workspace.generated.env in the worktree root.
'@
  exit 0
}

. "$PSScriptRoot/lib/paths.ps1"
$repoRoot = Get-CopilotRepoRoot
$worktreeRoot = if ($WorktreePath) { (Resolve-Path $WorktreePath).Path } else { Resolve-CopilotWorktreeRoot -RepoRoot $repoRoot }
$sourceRoot = Resolve-CopilotSourceRoot -RepoRoot $repoRoot

$scriptsDir = Join-Path $repoRoot 'scripts'
& "$scriptsDir/worktree-allocate-ports.ps1" -WorktreePath $worktreeRoot | Out-Null

$portsFile = Join-Path $worktreeRoot '.worktree-ports.env'
$forgeAppPort = $env:FORGE_APP_PORT
if (-not $forgeAppPort -and (Test-Path $portsFile)) {
  $match = Select-String -Path $portsFile -Pattern '^FORGE_APP_PORT=(\d+)' | Select-Object -First 1
  if ($match) { $forgeAppPort = $match.Matches.Groups[1].Value }
}
if (-not $forgeAppPort -and $env:COPILOT_PORT) {
  $forgeAppPort = $env:COPILOT_PORT
}

$prBase = if ($env:COPILOT_DEFAULT_BRANCH -and $env:COPILOT_DEFAULT_BRANCH -ne 'main') {
  $env:COPILOT_DEFAULT_BRANCH
}
else {
  'dev'
}

$copilotDir = Join-Path $worktreeRoot '.copilot'
New-Item -ItemType Directory -Force -Path $copilotDir | Out-Null

$lines = @(
  '# Auto-generated by scripts/copilot-workspace/generate-env.ps1 — do not commit',
  "MODME_WORKSPACE_NAME=$($env:COPILOT_WORKSPACE_NAME)",
  "MODME_WORKSPACE_PATH=$worktreeRoot",
  "MODME_ROOT_PATH=$sourceRoot",
  "MODME_PR_BASE_BRANCH=$prBase",
  "COPILOT_SCRIPT_TRIGGER=$($env:COPILOT_SCRIPT_TRIGGER)",
  "COPILOT_PORT=$($env:COPILOT_PORT)",
  "FORGE_APP_PORT=$forgeAppPort"
)

if (Test-Path $portsFile) {
  $lines += Get-Content $portsFile | Where-Object { $_ -notmatch '^#' -and $_ -match '=' }
}

$outFile = Join-Path $copilotDir 'workspace.generated.env'
Set-Content -Path $outFile -Value $lines -Encoding utf8
Write-Host "Wrote $outFile" -ForegroundColor Green
