#!/usr/bin/env node
/**
 * Run full PR triage pipeline (recommendation mode — no auto-merge).
 * Usage: node scripts/pr-triage/run-triage.mjs [--markdown] [--repo OWNER/REPO]
 */

import { execSync, spawnSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs, DEFAULT_REPO } from "./lib/gh.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");
const args = parseArgs(process.argv.slice(2));
const date = new Date().toISOString().slice(0, 10);

function runNode(script, extraArgs = []) {
  const r = spawnSync(process.execPath, [resolve(__dirname, script), ...extraArgs, "--repo", args.repo], {
    cwd: ROOT,
    encoding: "utf8",
    maxBuffer: 20 * 1024 * 1024,
  });
  if (r.status !== 0) {
    console.error(r.stderr || r.stdout);
    throw new Error(`${script} failed`);
  }
  return JSON.parse(r.stdout);
}

const queue = runNode("fetch-review-queue.mjs", ["--base", "dev", "--json"]);
const classificationDev = runNode("classify-pr.mjs", ["--base", "dev", "--json"]);
const classificationMain = runNode("classify-pr.mjs", ["--base", "main", "--json"]);

const commentSummaries = [];
for (const pr of queue.prs.slice(0, 10)) {
  try {
    const c = runNode("aggregate-pr-comments.mjs", ["--pr", String(pr.pr_number), "--json"]);
    commentSummaries.push({
      pr: pr.pr_number,
      title: pr.title,
      url: pr.url,
      high: c.totals.high,
      medium: c.totals.medium,
      low: c.totals.low,
      topActions: c.actionList.slice(0, 5),
    });
  } catch (e) {
    commentSummaries.push({ pr: pr.pr_number, error: String(e.message) });
  }
}

let changelogOk = true;
let changelogMsg = "ok";
try {
  execSync("node scripts/validate-changelog.mjs", { cwd: ROOT, encoding: "utf8", stdio: "pipe" });
} catch (e) {
  changelogOk = false;
  changelogMsg = e.stderr?.toString() || e.message;
}

const report = {
  date,
  mode: "recommendation",
  repo: args.repo,
  queue,
  devClassification: classificationDev,
  mainClassification: classificationMain,
  commentSummaries,
  changelog: { ok: changelogOk, message: changelogMsg },
  recommendations: [],
};

for (const c of commentSummaries) {
  if (c.high > 0) {
    report.recommendations.push({
      pr: c.pr,
      action: "fix_high_comments",
      detail: `${c.high} high-severity comment(s) — do not merge`,
    });
  } else if (c.medium === 0 && c.low !== undefined && c.high === 0) {
    report.recommendations.push({
      pr: c.pr,
      action: "merge_candidate",
      detail: "No high/medium comments — verify CI then squash merge",
    });
  }
}

for (const p of classificationMain.prs ?? []) {
  if (p.action === "close_stale" || p.action === "close_dependabot") {
    report.recommendations.push({
      pr: p.number,
      action: p.action,
      detail: p.reason,
    });
  } else if (p.action === "retarget_dev") {
    report.recommendations.push({
      pr: p.number,
      action: "retarget_dev",
      detail: p.reason,
    });
  } else if (p.action === "escalate_before_close") {
    report.recommendations.push({
      pr: p.number,
      action: "escalate_before_close",
      detail: p.reason,
    });
  }
}

const outDir = resolve(ROOT, "docs/pr-resolution/reports");
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
const reportPath = resolve(outDir, `triage-${date}.json`);
writeFileSync(reportPath, JSON.stringify(report, null, 2));

function buildMarkdownIssueBody() {
  let md = `## PR Triage — ${date}\n\n`;
  md += `**Mode:** recommendation (no auto-merge)\n\n`;
  md += `### Dev queue (${queue.total})\n\n`;
  md += "| PR | Title | High | Med | Low |\n|----|-------|------|-----|-----|\n";
  for (const c of commentSummaries) {
    if (c.error) continue;
    md += `| [#${c.pr}](${c.url}) | ${c.title?.slice(0, 40)} | ${c.high} | ${c.medium} | ${c.low} |\n`;
  }
  md += `\n### Recommendations\n\n`;
  for (const r of report.recommendations) {
    md += `- **PR #${r.pr}** — \`${r.action}\`: ${r.detail}\n`;
  }
  md += `\n### Stale main-targeting (${classificationMain.total})\n\n`;
  md += `| Action | Count |\n|--------|-------|\n`;
  for (const [k, v] of Object.entries(classificationMain.byAction ?? {})) {
    md += `| ${k} | ${v} |\n`;
  }
  md += `\n### Changelog\n\n${changelogOk ? "✓ Valid" : "✗ " + changelogMsg}\n`;
  md += `\n---\n*Generated by \`yarn pr:triage\` — report: \`docs/pr-resolution/reports/triage-${date}.json\`*\n`;
  return md;
}

const mdPath = resolve(outDir, `triage-${date}.md`);
writeFileSync(mdPath, buildMarkdownIssueBody());

if (args.format === "markdown") {
  console.log(buildMarkdownIssueBody());
} else {
  console.log(JSON.stringify({ ...report, reportPath, markdownPath: mdPath }, null, 2));
}
