/**
 * skills-molecule-generator.ts
 *
 * Generates Skill JSON files from CatalogueEntry records.
 * A "Skill" here matches the .agents/skills/ SKILL.md format used in
 * the repo: name, description, domain, trigger phrases, usage examples.
 *
 * @feature INBOX.ARTEFACT.GENERATE
 * @domain INBOX
 * @layer AGENT
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { CatalogueEntry } from './supabase-catalogue-fetcher.js';

export interface SkillJson {
  id: string;
  name: string;
  description: string;
  version: string;
  domain: string;
  triggerPhrases: string[];
  parameters: Record<string, unknown>;
  examples: Array<{ description: string; input: Record<string, unknown> }>;
  metadata: { schemaType: string; generatedAt: string; sourceEntryId?: string };
}

function getRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : {};
}

function getExamples(
  value: unknown
): Array<{ description: string; input: Record<string, unknown> }> {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.flatMap((example) => {
    const record = getRecord(example);
    const input = getRecord(record['input']);

    if (Object.keys(record).length === 0) {
      return [];
    }

    return [
      {
        description:
          typeof record['description'] === 'string' ? record['description'] : 'Generated example',
        input,
      },
    ];
  });
}

export function generateSkillFromCatalogueEntry(entry: CatalogueEntry): SkillJson {
  const schema = getRecord(entry.schema);
  const parameterFields = getRecord(schema['properties']);

  return {
    id: entry.slug,
    name: entry.name,
    description: typeof schema['description'] === 'string' ? schema['description'] : `${entry.name} skill`,
    version: entry.version,
    domain: entry.schemaType === 'agent' ? 'AGENT' : entry.schemaType.toUpperCase(),
    triggerPhrases:
      Array.isArray(schema['triggerPhrases']) && schema['triggerPhrases'].every((item) => typeof item === 'string')
        ? (schema['triggerPhrases'] as string[])
        : [entry.name.toLowerCase()],
    parameters: parameterFields,
    examples: getExamples(schema['examples']),
    metadata: {
      schemaType: entry.schemaType,
      generatedAt: new Date().toISOString(),
      sourceEntryId: entry.id,
    },
  };
}

export function writeSkillToFile(skill: SkillJson, outputDir: string): string {
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const skillDir = join(outputDir, skill.id);
  if (!existsSync(skillDir)) {
    mkdirSync(skillDir, { recursive: true });
  }

  const skillFile = join(skillDir, 'skill.json');
  writeFileSync(skillFile, JSON.stringify(skill, null, 2), 'utf-8');

  const skillMdFile = join(skillDir, 'SKILL.md');
  if (!existsSync(skillMdFile)) {
    const md = `# ${skill.name}

${skill.description}

## Trigger Phrases
${skill.triggerPhrases.map((triggerPhrase) => `- ${triggerPhrase}`).join('\n')}

## Domain
${skill.domain}

---
*Generated by skills-molecule-generator ${skill.metadata.generatedAt}*
`;
    writeFileSync(skillMdFile, md, 'utf-8');
  }

  return skillFile;
}

export async function generateSkillsFromCatalogue(
  entries: CatalogueEntry[],
  outputDir: string,
  options: { dryRun?: boolean; schemaType?: string } = {}
): Promise<{ generated: string[]; skipped: number }> {
  const skillEntries = entries.filter(
    (entry) => !options.schemaType || entry.schemaType === options.schemaType
  );
  const generated: string[] = [];

  for (const entry of skillEntries) {
    const skill = generateSkillFromCatalogueEntry(entry);

    if (options.dryRun) {
      console.log(`[dry-run] Would generate skill: ${skill.id}`);
      generated.push(skill.id);
      continue;
    }

    const skillPath = writeSkillToFile(skill, outputDir);
    console.log(`[skills-generator] Generated: ${skillPath}`);
    generated.push(skillPath);
  }

  return {
    generated,
    skipped: entries.length - skillEntries.length,
  };
}
