/**
 * storybook-story-generator.ts
 *
 * Generates Storybook story files (.stories.tsx) from component-type
 * CatalogueEntry and InboxEntry records.
 *
 * @feature INBOX.ARTEFACT.GENERATE
 * @domain INBOX
 * @layer AGENT
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { CatalogueEntry } from './supabase-catalogue-fetcher.js';

type StorySource = CatalogueEntry | Record<string, unknown>;

function isCatalogueEntry(entry: StorySource): entry is CatalogueEntry {
  return 'schemaType' in entry;
}

function sanitiseComponentName(value: string): string {
  const stripped = value.replace(/[^a-zA-Z0-9]/g, '').replace(/^\d+/, '');
  return stripped.length > 0 ? stripped : 'GeneratedComponent';
}

function getDescription(entry: StorySource, name: string): string {
  if (!isCatalogueEntry(entry)) {
    return typeof entry['summary'] === 'string' ? entry['summary'] : `${name} component`;
  }

  return typeof entry.schema['description'] === 'string'
    ? entry.schema['description']
    : `${name} component`;
}

function getStoryProps(entry: StorySource): string[] {
  if (!isCatalogueEntry(entry)) {
    return Array.isArray(entry['tags'])
      ? entry['tags'].filter((tag): tag is string => typeof tag === 'string').slice(0, 3)
      : [];
  }

  const properties = entry.schema['properties'];
  if (typeof properties !== 'object' || properties === null) {
    return [];
  }

  return Object.keys(properties);
}

export function generateStorybookStory(
  entry: StorySource,
  outputDir: string
): string {
  const name = isCatalogueEntry(entry)
    ? entry.name
    : typeof entry['title'] === 'string'
      ? entry['title']
      : 'UnknownComponent';
  const slug = isCatalogueEntry(entry) ? entry.slug : String(entry['id'] ?? 'unknown');
  const componentName = sanitiseComponentName(name);
  const description = getDescription(entry, name);
  const props = getStoryProps(entry);

  const story = `/**
 * Storybook story for ${componentName}
 * @feature UI.COMPONENT.STORY
 * Generated by storybook-story-generator
 * Source: ${slug}
 */
import type { Meta, StoryObj } from '@storybook/react';

// TODO: Replace with actual component import
// import { ${componentName} } from '@repo/design-system/components/${componentName}';

const PlaceholderComponent = ({
  children,
  ...props
}: Record<string, unknown> & { children?: React.ReactNode }) => (
  <div data-component="${slug}" {...(props as React.HTMLAttributes<HTMLDivElement>)}>
    {children ?? ${JSON.stringify(`${name} placeholder`)}}
  </div>
);

const meta = {
  title: 'Generated/${componentName}',
  component: PlaceholderComponent,
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component: ${JSON.stringify(description)},
      },
    },
  },
  tags: ['autodocs', 'generated'],
  argTypes: {
${props.map((propName) => `    ${propName}: { control: 'text', description: ${JSON.stringify(`${propName} prop`)} },`).join('\n')}
  },
} satisfies Meta<typeof PlaceholderComponent>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
${props.map((propName) => `    ${propName}: ${JSON.stringify(`${propName} value`)},`).join('\n')}
  },
};

export const Empty: Story = {
  args: {},
};
`;

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = join(outputDir, `${componentName}.stories.tsx`);
  writeFileSync(outputPath, story, 'utf-8');
  return outputPath;
}

export async function generateStoriesFromCatalogue(
  entries: StorySource[],
  outputDir: string,
  options: { dryRun?: boolean } = {}
): Promise<{ generated: string[]; skipped: number }> {
  const componentEntries = entries.filter((entry) => {
    if (isCatalogueEntry(entry)) {
      return entry.schemaType === 'component' || entry.schemaType === 'storybook';
    }

    return entry['entry_type'] === 'component';
  });

  const generated: string[] = [];

  for (const entry of componentEntries) {
    if (options.dryRun) {
      const name = isCatalogueEntry(entry)
        ? entry.name
        : typeof entry['title'] === 'string'
          ? entry['title']
          : 'unknown';
      console.log(`[dry-run] Would generate story for: ${name}`);
      generated.push(name);
      continue;
    }

    const storyPath = generateStorybookStory(entry, outputDir);
    console.log(`[storybook-generator] Generated: ${storyPath}`);
    generated.push(storyPath);
  }

  return {
    generated,
    skipped: entries.length - componentEntries.length,
  };
}
