# ModMe unified env bootstrap — root .env, worktree ports, next-forge database env.
# Dot-source from scripts or: Import-Module pattern via functions below.

. (Join-Path $PSScriptRoot 'read-dotenv.ps1')

function Get-ModMeRepoRoot {
    param([string]$HintPath = $PSScriptRoot)

    $dir = $HintPath
    for ($i = 0; $i -lt 6; $i++) {
        $pkg = Join-Path $dir 'package.json'
        if (Test-Path $pkg) {
            $name = (Get-Content $pkg -Raw | ConvertFrom-Json).name
            if ($name -eq 'monorepo_modme-root') {
                return (Resolve-Path $dir).Path
            }
        }
        $parent = Split-Path $dir -Parent
        if (-not $parent -or $parent -eq $dir) { break }
        $dir = $parent
    }
    throw "Could not locate ModMe repo root from $HintPath"
}

function Import-DotEnvFileToProcess {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [switch]$Overwrite
    )

    if (-not (Test-Path $Path)) { return 0 }

    $count = 0
    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith('#')) { return }
        if ($line -match '^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
            $key = $Matches[1]
            $value = $Matches[2].Trim().Trim('"').Trim("'")
            if ($Overwrite -or -not (Get-Item -Path "env:$key" -ErrorAction SilentlyContinue)) {
                Set-Item -Path "env:$key" -Value $value
                $count++
            }
        }
    }
    return $count
}

function Import-ModMeEnv {
    param(
        [string]$RepoRoot = (Get-ModMeRepoRoot),
        [switch]$IncludeForgeAppLocal,
        [switch]$Quiet
    )

    $loaded = @{}

    $rootEnv = Join-Path $RepoRoot '.env'
    $n = Import-DotEnvFileToProcess -Path $rootEnv
    if ($n -gt 0) { $loaded['root'] = $n }

    $portsFile = Join-Path $RepoRoot '.worktree-ports.env'
    $n = Import-DotEnvFileToProcess -Path $portsFile -Overwrite
    if ($n -gt 0) { $loaded['ports'] = $n }

    $forgeDb = Join-Path $RepoRoot 'next-forge\packages\database\.env'
    $n = Import-DotEnvFileToProcess -Path $forgeDb
    if ($n -gt 0) { $loaded['forge-db'] = $n }

    if ($IncludeForgeAppLocal) {
        $appLocal = Join-Path $RepoRoot 'next-forge\apps\app\.env.local'
        $n = Import-DotEnvFileToProcess -Path $appLocal
        if ($n -gt 0) { $loaded['forge-app'] = $n }
    }

    Set-Item -Path env:MONOREPO_MODME_ROOT -Value $RepoRoot
    Set-Item -Path env:MODME_ENV_LOADED -Value '1'

    # ModMe URL defaults when ports env present
    if ($env:FORGE_APP_PORT -and -not $env:NEXT_PUBLIC_APP_URL) {
        Set-Item env:NEXT_PUBLIC_APP_URL "http://localhost:$($env:FORGE_APP_PORT)"
    }
    if ($env:FORGE_WEB_PORT -and -not $env:NEXT_PUBLIC_WEB_URL) {
        Set-Item env:NEXT_PUBLIC_WEB_URL "http://localhost:$($env:FORGE_WEB_PORT)"
    }
    if ($env:FORGE_API_PORT -and -not $env:NEXT_PUBLIC_API_URL) {
        Set-Item env:NEXT_PUBLIC_API_URL "http://localhost:$($env:FORGE_API_PORT)"
    }

    if (-not $Quiet) {
        $summary = ($loaded.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join ', '
        if ($summary) {
            Write-Host "[modme-env] loaded ($summary)" -ForegroundColor DarkGray
        }
    }

    return $loaded
}

function Write-ModMeRuntimeEnvFile {
    param(
        [string]$RepoRoot = (Get-ModMeRepoRoot),
        [string]$OutPath = (Join-Path $RepoRoot '.vscode\.env.runtime')
    )

    Import-ModMeEnv -RepoRoot $RepoRoot -IncludeForgeAppLocal -Quiet | Out-Null

    $keys = @{}
    foreach ($file in @(
            (Join-Path $RepoRoot '.env')
            (Join-Path $RepoRoot '.worktree-ports.env')
            (Join-Path $RepoRoot 'next-forge\packages\database\.env')
            (Join-Path $RepoRoot 'next-forge\apps\app\.env.local')
            (Join-Path $RepoRoot 'next-forge\apps\api\.env.local')
            (Join-Path $RepoRoot 'next-forge\apps\web\.env.local')
        )) {
        if (-not (Test-Path $file)) { continue }
        foreach ($entry in (Get-DotEnvMap -Path $file).GetEnumerator()) {
            if ($entry.Value) { $keys[$entry.Key] = $entry.Value }
        }
    }

    if ($env:MONOREPO_MODME_ROOT) { $keys['MONOREPO_MODME_ROOT'] = $env:MONOREPO_MODME_ROOT }

    $dir = Split-Path $OutPath -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

    $lines = @('# Generated by modme-env-bootstrap - do not commit')
    foreach ($key in ($keys.Keys | Sort-Object)) {
        $lines += "$key=$($keys[$key])"
    }
    Set-Content -Path $OutPath -Value ($lines -join "`n") -Encoding UTF8
    return $OutPath
}

function Test-ModMeEnv {
    param([string]$RepoRoot = (Get-ModMeRepoRoot))

    $issues = @()
    if (-not (Test-Path (Join-Path $RepoRoot '.env'))) {
        $issues += 'missing root .env (copy from .env.example)'
    }

    $runtime = Write-ModMeRuntimeEnvFile -RepoRoot $RepoRoot
    if (-not (Test-Path $runtime)) {
        $issues += 'failed to write .vscode/.env.runtime'
    }

    foreach ($key in @('MONOREPO_MODME_ROOT')) {
        if (-not (Get-Item -Path "env:$key" -ErrorAction SilentlyContinue)) {
            $issues += "env:$key not set after bootstrap"
        }
    }

    return @{
        Ok     = ($issues.Count -eq 0)
        Issues = $issues
        RuntimeEnvFile = $runtime
    }
}
