#!/usr/bin/env bun
/**
 * Emit Zod module snapshots from molecule parameterSchema via schema-crawler.ts.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { generateZodFromJSONSchema } from "../GenerativeUI_monorepo/apps/agent-generator/src/mcp-registry/schema-crawler.ts";
import { MoleculeLibrary } from "../GenerativeUI_monorepo/apps/agent-generator/src/mcp-registry/molecule-generator.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const ZOD_DIR = resolve(ROOT, "data/molecule-index/zod");

function main() {
  mkdirSync(ZOD_DIR, { recursive: true });

  const molecules = Object.values(MoleculeLibrary).map((factory) => factory());
  let written = 0;

  for (const molecule of molecules) {
    const schemaName = `${molecule.id}_parameters`;
    const output = generateZodFromJSONSchema(
      molecule.parameterSchema,
      schemaName
    );
    const moduleContent = `/**
 * Auto-generated by schema-crawler export (molecule-index orchestrator)
 * Molecule: ${molecule.id}
 */

import { z } from 'zod';

${output.typeDefinition}

export const ${schemaName}Schema = ${output.zodCode.trim()};

${output.validatorCode}
`;
    writeFileSync(resolve(ZOD_DIR, `${molecule.id}.schema.ts`), moduleContent, "utf8");
    written += 1;
  }

  const indexContent = molecules
    .map((m) => `export * from './${m.id}.schema';`)
    .join("\n");

  writeFileSync(
    resolve(ZOD_DIR, "index.ts"),
    `// Auto-generated barrel\n\n${indexContent}\n`,
    "utf8"
  );

  console.log(JSON.stringify({ ok: true, modulesWritten: written, zodDir: "data/molecule-index/zod" }));
}

main();
