"""
Upload Copilot chat examples to Phoenix dataset via MCP.

This script:
1. Reads phoenix_remaining_examples.json (generated by prepare_all_examples.py)
2. Uploads examples to Phoenix dataset in batches
3. Uses Phoenix MCP server to add dataset examples

Usage:
    python scripts/upload_to_phoenix.py
    python scripts/upload_to_phoenix.py --batch-size 5
    python scripts/upload_to_phoenix.py --dataset copilot-research
"""
import argparse
import json
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))


def load_examples(file_path: str) -> list[dict]:
    """Load examples from JSON file."""
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def upload_batch_to_phoenix(examples: list[dict], dataset_name: str) -> dict:
    """
    Upload a batch of examples to Phoenix.

    Note: This function would use the MCP Phoenix client to upload.
    For now, it returns mock response. Integrate with actual MCP client.
    """
    # TODO: Integrate with Phoenix MCP client
    # from phoenix_client import add_dataset_examples
    # return add_dataset_examples(datasetName=dataset_name, examples=examples)

    print(f"Uploading {len(examples)} examples to dataset '{dataset_name}'...")
    return {"status": "success","message": f"Uploaded {len(examples)} examples"}


def main():
    parser = argparse.ArgumentParser(description="Upload Copilot chat examples to Phoenix dataset")
    parser.add_argument(
        "--file",
        default="phoenix_remaining_examples.json",
        help="JSON file with examples (default: phoenix_remaining_examples.json)"
    )
    parser.add_argument(
        "--dataset",
        default="copilot-research",
        help="Phoenix dataset name (default: copilot-research)"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=10,
        help="Number of examples per batch (default: 10)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print examples without uploading"
    )

    args = parser.parse_args()

    # Load examples
    print(f"Loading examples from {args.file}...")
    examples = load_examples(args.file)
    print(f"Loaded {len(examples)} examples")

    if args.dry_run:
        print("\nDRY RUN - First 3 examples:")
        for i, ex in enumerate(examples[:3], 1):
            print(f"\n{i}. {ex['input']['user_message'][:80]}...")
            print(f"   Model: {ex['input']['model']}, Turn: {ex['input'].get('turn', 0)}")
            print(f"   Response: {ex['output']['assistant_response'][:80]}...")
        return

    # Upload in batches
    total_uploaded = 0
    batch_num = 1

    for i in range(0, len(examples), args.batch_size):
        batch = examples[i:i + args.batch_size]
        print(f"\nBatch {batch_num}/{(len(examples) + args.batch_size - 1) // args.batch_size}:")

        result = upload_batch_to_phoenix(batch, args.dataset)

        if result.get("status") == "success":
            total_uploaded += len(batch)
            print(f"✅ Uploaded {len(batch)} examples (Total: {total_uploaded}/{len(examples)})")
        else:
            print(f"❌ Failed to upload batch: {result.get('message')}")
            break

        batch_num += 1

    print(f"\n🎉 Upload complete! Total: {total_uploaded}/{len(examples)} examples uploaded to '{args.dataset}'")


if __name__ == "__main__":
    main()
