# Monorepo_ModMe — Per-worktree port allocation
# Derives a stable slot (0-9) from the worktree folder name and writes .worktree-ports.env

param(
  [Parameter(Mandatory = $false)]
  [string]$WorktreePath = (Get-Location).Path,

  [Parameter(Mandatory = $false)]
  [string]$ManifestPath
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$RepoRoot = Split-Path -Parent $ScriptDir

if (-not $ManifestPath) {
  $ManifestPath = Join-Path $ScriptDir "launch-manifest.json"
}

if (-not (Test-Path $ManifestPath)) {
  Write-Error "Launch manifest not found: $ManifestPath"
}

$manifest = Get-Content -Raw $ManifestPath | ConvertFrom-Json

function Get-AppPort($appId) {
  $app = $manifest.apps | Where-Object { $_.id -eq $appId } | Select-Object -First 1
  if (-not $app -or -not $app.port) {
    Write-Error "Port not defined for app '$appId' in launch-manifest.json"
  }
  return [int]$app.port
}

$baseVibeWeb = Get-AppPort "vibe-web-app"
$baseWebDashboard = Get-AppPort "web-dashboard"
$baseAgentServer = Get-AppPort "agent-server"
$baseExampleNext = Get-AppPort "example-next"
$baseExampleReact = Get-AppPort "example-react"
$baseForgeApp = Get-AppPort "forge-app"
$baseForgeWeb = Get-AppPort "forge-web"
$baseForgeApi = Get-AppPort "forge-api"
$baseForgeDocs = Get-AppPort "forge-docs"
$baseForgeStorybook = Get-AppPort "forge-storybook"

$folderName = Split-Path -Leaf $WorktreePath
$hashBytes = [System.Security.Cryptography.SHA256]::Create().ComputeHash(
  [System.Text.Encoding]::UTF8.GetBytes($folderName)
)
$slot = [int]($hashBytes[0] % 10)

$offset = $slot * 10

$ports = @{
  WORKTREE_SLOT        = $slot
  VIBE_WEB_PORT        = $baseVibeWeb + $offset
  WEB_DASHBOARD_PORT   = $baseWebDashboard + $offset
  AGENT_SERVER_PORT    = $baseAgentServer + $offset
  EXAMPLE_NEXT_PORT    = $baseExampleNext + $offset
  EXAMPLE_REACT_PORT   = $baseExampleReact + $offset
  FORGE_APP_PORT       = $baseForgeApp + $offset
  FORGE_WEB_PORT       = $baseForgeWeb + $offset
  FORGE_API_PORT       = $baseForgeApi + $offset
  FORGE_DOCS_PORT      = $baseForgeDocs + $offset
  FORGE_STORYBOOK_PORT = $baseForgeStorybook + $offset
}

$envFile = Join-Path $WorktreePath ".worktree-ports.env"
$lines = @(
  "# Auto-generated by scripts/worktree-allocate-ports.ps1 - do not commit",
  "# Worktree folder: $folderName",
  "WORKTREE_SLOT=$($ports.WORKTREE_SLOT)",
  "VIBE_WEB_PORT=$($ports.VIBE_WEB_PORT)",
  "WEB_DASHBOARD_PORT=$($ports.WEB_DASHBOARD_PORT)",
  "AGENT_SERVER_PORT=$($ports.AGENT_SERVER_PORT)",
  "EXAMPLE_NEXT_PORT=$($ports.EXAMPLE_NEXT_PORT)",
  "EXAMPLE_REACT_PORT=$($ports.EXAMPLE_REACT_PORT)",
  "FORGE_APP_PORT=$($ports.FORGE_APP_PORT)",
  "FORGE_WEB_PORT=$($ports.FORGE_WEB_PORT)",
  "FORGE_API_PORT=$($ports.FORGE_API_PORT)",
  "FORGE_DOCS_PORT=$($ports.FORGE_DOCS_PORT)",
  "FORGE_STORYBOOK_PORT=$($ports.FORGE_STORYBOOK_PORT)",
  "NEXT_PUBLIC_AGENT_SERVER_WS_URL=ws://localhost:$($ports.AGENT_SERVER_PORT)/ws/agent"
)

Set-Content -Path $envFile -Value $lines -Encoding utf8

Write-Host "Allocated ports for '$folderName' (slot $slot):" -ForegroundColor Green
$ports.GetEnumerator() | Sort-Object Name | ForEach-Object {
  Write-Host "   $($_.Name)=$($_.Value)"
}
Write-Host "   Written: $envFile"

return $envFile
