#!/usr/bin/env bash
set -e
# create_pr.sh – push feature branch and open a PR via GitHub CLI
# Assumes current directory is the worktree created by devops_prepare_commit.sh

# Verify gh CLI is available
if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI (gh) not found. Please install it to create PRs automatically."
  exit 1
fi

# Push the feature branch to origin
git push -u origin "$(git rev-parse --abbrev-ref HEAD)"

# Create PR
PR_TITLE="Quality Playbook – automated fixes"
PR_BODY="This PR adds Playwright tests generated by the Quality Playbook, includes architectural review notes, and follows DevOps best practices.\n\n- Generated Playwright tests for uncovered UI components\n- SE Architect review attached (quality/ARCHITECT_REVIEW.md)\n- All lint, test, and build checks passed"

# Use gh to create PR targeting dev branch
gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --base dev \
  --label "quality,automation"

echo "Pull request created successfully."
