'use client';

import { useAgentState } from '@/hooks/useAgentState';
import { AgentAction } from '@generative-ui/shared-schemas';
import { useMemo } from 'react';

/**
 * GenerativeCanvas component renders UI based on AI agent state
 * This component displays dynamic UI components generated by the AI agent
 */
export default function GenerativeCanvas() {
  const { state, isConnected, error } = useAgentState();

  const renderedComponents = useMemo(() => {
    if (!state?.actions) return null;

    return state.actions
      .filter((action: AgentAction) => action.type === 'render')
      .map((action: AgentAction) => {
        return (
          <div
            key={action.id}
            className="p-6 mb-4 bg-white dark:bg-gray-800 rounded-lg shadow-lg"
          >
            {renderComponent(action)}
          </div>
        );
      });
  }, [state?.actions]);

  if (error) {
    return (
      <div className="p-6 bg-red-100 dark:bg-red-900 rounded-lg">
        <h2 className="text-xl font-bold text-red-800 dark:text-red-200 mb-2">
          Error
        </h2>
        <p className="text-red-700 dark:text-red-300">{error}</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-4 mb-6">
        <div className="flex items-center gap-2">
          <div
            className={`w-3 h-3 rounded-full ${
              isConnected ? 'bg-green-500' : 'bg-red-500'
            }`}
          />
          <span className="text-sm text-gray-600 dark:text-gray-400">
            {isConnected ? 'Connected' : 'Disconnected'}
          </span>
        </div>
        {state?.status && (
          <div className="text-sm text-gray-600 dark:text-gray-400">
            Status: <span className="font-medium">{state.status}</span>
          </div>
        )}
      </div>

      {!renderedComponents || renderedComponents.length === 0 ? (
        <div className="p-12 text-center bg-gray-100 dark:bg-gray-800 rounded-lg">
          <p className="text-gray-600 dark:text-gray-400">
            No components to display yet. Connect to the agent server to see
            generated UI components.
          </p>
        </div>
      ) : (
        renderedComponents
      )}
    </div>
  );
}

/**
 * Renders a component based on the agent action
 */
function renderComponent(action: AgentAction) {
  const { componentType, props, content } = action;

  switch (componentType) {
    case 'text':
      return (
        <div>
          <h3 className="text-xl font-bold mb-2">
            {props?.title || 'Text Component'}
          </h3>
          <p className="text-gray-700 dark:text-gray-300">
            {content || props?.text || 'No content'}
          </p>
        </div>
      );

    case 'card':
      return (
        <div>
          <h3 className="text-xl font-bold mb-2">
            {props?.title || 'Card Component'}
          </h3>
          <p className="text-gray-700 dark:text-gray-300 mb-4">
            {props?.description || content}
          </p>
          {props?.data && (
            <pre className="p-4 bg-gray-100 dark:bg-gray-900 rounded text-sm overflow-x-auto">
              {JSON.stringify(props.data, null, 2)}
            </pre>
          )}
        </div>
      );

    case 'list':
      return (
        <div>
          <h3 className="text-xl font-bold mb-2">
            {props?.title || 'List Component'}
          </h3>
          <ul className="list-disc list-inside space-y-1">
            {Array.isArray(content) ? (
              content.map((item: any, index: number) => (
                <li key={index} className="text-gray-700 dark:text-gray-300">
                  {typeof item === 'string' ? item : JSON.stringify(item)}
                </li>
              ))
            ) : (
              <li className="text-gray-700 dark:text-gray-300">
                {String(content)}
              </li>
            )}
          </ul>
        </div>
      );

    default:
      return (
        <div>
          <h3 className="text-xl font-bold mb-2">
            {componentType || 'Unknown Component'}
          </h3>
          <div className="p-4 bg-gray-100 dark:bg-gray-900 rounded">
            <pre className="text-sm overflow-x-auto">
              {JSON.stringify({ props, content }, null, 2)}
            </pre>
          </div>
        </div>
      );
  }
}
